package ventanas;

import clases.Conexion;
import java.awt.Image;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.DocWriter;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Font;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;

import java.awt.Toolkit;
import java.io.FileOutputStream;
import java.net.ConnectException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.tools.Tool;

public class Capturista extends javax.swing.JFrame {

    String user, nombre_usuario;
    int sesion_usuario;

    public Capturista() {
        initComponents();
        user = Login.user;
        sesion_usuario = Administrador.sesion_usuario;

        setSize(550, 330);
        setTitle("Capturista - " + "Sesion de " + user);
        setResizable(false);
        setLocationRelativeTo(null);

        if (sesion_usuario == 1) {
            setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        } else {
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select nombre_usuario from usuarios where username = '" + user + "'");
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                nombre_usuario = rs.getString("nombre_usuario");
                jLabel_NombreUsuario.setText("Bienvenido " + nombre_usuario);
            }

        } catch (SQLException e) {
            System.out.println("Error en consultar nombre de Capturista.");
        }
    }

    @Override
    public Image getIconImage() {
//luego de crear el metodo lo programamos, creamos un ob. y obtenemos la imagen del icono a colocar en interfaz.
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;//se o si hay q hacer el retorno del objeto.
/*de igual forma debemos ir a JFrame, clic derecho y propiedades, IconImage clic en ..., value from existing component,
        property, Iconimage, ok ok*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_NombreUsuario = new javax.swing.JLabel();
        jButton_RegistrarCliente = new javax.swing.JButton();
        jButton_GestionarCliente = new javax.swing.JButton();
        jButton_ImprimirCliente = new javax.swing.JButton();
        jLabel_Registrar = new javax.swing.JLabel();
        jLabel_Gestionar = new javax.swing.JLabel();
        jLabel_Imprimir = new javax.swing.JLabel();
        jLabel_footer = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_NombreUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_NombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NombreUsuario.setText("jLabel1");
        getContentPane().add(jLabel_NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton_RegistrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jButton_RegistrarCliente.setBorder(null);
        jButton_RegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_RegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 120, 100));

        jButton_GestionarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/informationuser.png"))); // NOI18N
        jButton_GestionarCliente.setBorder(null);
        jButton_GestionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GestionarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_GestionarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 120, 100));

        jButton_ImprimirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/impresora.png"))); // NOI18N
        jButton_ImprimirCliente.setBorder(null);
        jButton_ImprimirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ImprimirClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ImprimirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 120, 100));

        jLabel_Registrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_Registrar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Registrar.setText("Registrar Clientes");
        getContentPane().add(jLabel_Registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel_Gestionar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_Gestionar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Gestionar.setText("Gestionar Clientes");
        getContentPane().add(jLabel_Gestionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 180, -1, -1));

        jLabel_Imprimir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel_Imprimir.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Imprimir.setText("Imprimir Clientes");
        getContentPane().add(jLabel_Imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        jLabel_footer.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel_footer.setText("Creado por Luna Fabio");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarClienteActionPerformed
        Registro_Cliente registro_cliente = new Registro_Cliente();
        registro_cliente.setVisible(true);
    }//GEN-LAST:event_jButton_RegistrarClienteActionPerformed

    private void jButton_GestionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GestionarClienteActionPerformed
        Gestionar_Clientes gestionCliente = new Gestionar_Clientes();
        gestionCliente.setVisible(true);
    }//GEN-LAST:event_jButton_GestionarClienteActionPerformed

    private void jButton_ImprimirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ImprimirClienteActionPerformed

        Document documento = new Document();//si o si creamos un ob de la clase Document.
        try {

            String ruta = System.getProperty("user.home");//estas 2 lineas son del lugar de guardado del pdf.
            PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Desktop/" + " Listado de clientes "+ " .pdf"));
    //3 lineas d obtencion de la imagen.
            com.itextpdf.text.Image header = com.itextpdf.text.Image.getInstance("src/images/BannerPDF.jpg");
            header.scaleToFit(650, 1000);
            header.setAlignment(Chunk.ALIGN_CENTER);
    //4 lineas parrafo y sus modif.
            Paragraph parrafo = new Paragraph();
            parrafo.setAlignment(Paragraph.ALIGN_CENTER);
            parrafo.add("Listado de clientes \n \n");
            parrafo.setFont(FontFactory.getFont("Tahoma" + 18 + Font.BOLD + BaseColor.DARK_GRAY));
    //guardado de doc.. header y parrafo creado anteriormente.
            documento.open();
            documento.add(header);
            documento.add(parrafo);
    // creo ob de la clase PdfTable y agrego las celdas(columnas) con sus nombres.
            PdfPTable tabla = new PdfPTable(5);
            tabla.addCell("ID");
            tabla.addCell("Nombre");
            tabla.addCell("Email");
            tabla.addCell("Telefono");
            tabla.addCell("Direccion");
            
            try {
                Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement("select * from cliente ");
            ResultSet rs = pst.executeQuery();
            
                if (rs.next()) {
                    do {                        
                        tabla.addCell(rs.getString(1));//agrego celdas con la ubicacion ordenada de lo q viene de la BD.
                        tabla.addCell(rs.getString(2));
                        tabla.addCell(rs.getString(3));
                        tabla.addCell(rs.getString(4));
                        tabla.addCell(rs.getString(5));
                        
                    } while (rs.next());
                    documento.add(tabla);//agrego la tabla al doc.
                }
            } catch (SQLException e) {
                System.err.println("Error al generar lista de clientes." + e);
            }
            documento.close();
            JOptionPane.showMessageDialog(null, "¡Lista de cliente guardado correctamente!");
        } catch (Exception e) {
            System.err.println("ERROR al cargar PDF." + e);   
        }
    }//GEN-LAST:event_jButton_ImprimirClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Capturista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Capturista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_GestionarCliente;
    private javax.swing.JButton jButton_ImprimirCliente;
    private javax.swing.JButton jButton_RegistrarCliente;
    private javax.swing.JLabel jLabel_Gestionar;
    private javax.swing.JLabel jLabel_Imprimir;
    private javax.swing.JLabel jLabel_NombreUsuario;
    private javax.swing.JLabel jLabel_Registrar;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_footer;
    // End of variables declaration//GEN-END:variables
}
