package ventanas;

import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class Grafica_Marcas extends javax.swing.JFrame {

    String user;
    int Acer, Apple, Samsung, Lenovo, MSI;
    
    String [] vector_tipo_marca  = new String [5]; 
    int [] vector_cantidad_marca = new int [5];
    
    public Grafica_Marcas() {
        initComponents();
        user = Login.user;

        setTitle("Tecnico - Sesión de " + user);
        setSize(440,400);
        setResizable(true);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_wallpaper.getWidth(),
                jLabel_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_wallpaper.setIcon(icono);
        this.repaint();
        
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
            "select marca, count(marca) as Marcas from equipos group by marca");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                int posicion = 0;
                do {                    
                    vector_tipo_marca[posicion] = rs.getString(1);
                    vector_cantidad_marca[posicion] = rs.getInt(2);
                    
                    if (vector_tipo_marca[posicion].equalsIgnoreCase("Acer")) {
                        Acer = vector_cantidad_marca[posicion];
                    } else if (vector_tipo_marca[posicion].equalsIgnoreCase("Apple")) {
                        Apple = vector_cantidad_marca[posicion];
                    } else if (vector_tipo_marca[posicion].equalsIgnoreCase("Samsung")){
                        Samsung = vector_cantidad_marca[posicion];
                    } else if (vector_tipo_marca[posicion].equalsIgnoreCase("Lenovo")) {
                        Lenovo = vector_cantidad_marca[posicion];
                    } else if (vector_tipo_marca[posicion].equalsIgnoreCase("MSI")){
                        MSI = vector_cantidad_marca[posicion];
                    }
                    posicion++;
                } while (rs.next());
            }
            repaint();
        } catch (SQLException e) {
            System.err.println("¡ERROR! no conecata a base de datos" + e);
            JOptionPane.showMessageDialog(null, "ERROR al consultar datos. Contacte al administrador.");           
        }
    }

    @Override
    public Image getIconImage() {
//luego de crear el metodo lo programamos, creamos un ob. y obtenemos la imagen del icono a colocar en interfaz.
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;//se o si hay q hacer el retorno del objeto.
/*de igual forma debemos ir a JFrame, clic derecho y propiedades, IconImage clic en ..., value from existing component,
        property, Iconimage, ok ok*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_footer = new javax.swing.JLabel();
        jLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Titulo.setText("Gráfica de marcas");
        getContentPane().add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, 20));

        jLabel_footer.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel_footer.setText("Creado por Luna Fabio");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, -1));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 442, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafica_Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafica_Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafica_Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafica_Marcas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Grafica_Marcas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JLabel jLabel_wallpaper;
    // End of variables declaration//GEN-END:variables
 
    @Override
    public void paint(Graphics g){
        super.paint(g);
        
        int grados_total_marca = Acer + Apple + Samsung  + Lenovo + MSI;
        
        int grados_acer = Acer * 360 / grados_total_marca;
        int grados_apple = Apple * 360 / grados_total_marca;
        int grados_samsung = Samsung * 360 / grados_total_marca;
        int grados_lenovo = Lenovo * 360 / grados_total_marca;
        int grados_msi = MSI *360 / grados_total_marca;
        
        g.setColor(new Color(255,0,0));
        g.fillArc(80, 100, 200, 200, 0, grados_acer);
        g.fillRect(300, 100, 20, 20);
        g.drawString(Acer + " Acer", 330, 115);
        
        
        g.setColor(new Color(0, 255,0));
        g.fillArc(80, 100, 200, 200,grados_acer, grados_apple);
        g.fillRect(300, 140, 20, 20);
        g.drawString(Apple + " Apple", 330, 155);
        
        g.setColor(new Color(0,0,255));
        g.fillArc(80, 100, 200, 200,grados_acer + grados_apple, grados_samsung);
        g.fillRect(300, 180, 20, 20);
        g.drawString(Samsung + " Samsung", 330, 195);
        
        g.setColor(new Color(0,0,0));
        g.fillArc(80, 100, 200, 200, grados_acer + grados_apple + grados_samsung, grados_lenovo);
        g.fillRect(300, 220, 20, 20);
        g.drawString(Lenovo + " Lenovo", 330, 235);
        
        g.setColor(new Color(255,255,255));
        g.fillArc(80, 100, 200, 200,grados_acer + grados_apple + grados_samsung + grados_lenovo, grados_msi);
        g.fillRect(300, 260, 20, 20);
        g.drawString(MSI + " MSI", 330, 275);   
    }
}
