package ventanas;

import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.tools.Tool;

public class Informacion_Equipo_Tecnico extends javax.swing.JFrame {
    //creamos solo estas var para traer datos de otras ventanas.
    int idEquipo = 0;
    String user = "";
    
    public Informacion_Equipo_Tecnico() {
        initComponents();
        user = Login.user;
        idEquipo = Gestionar_equipos.IDequipo_update;
        
        //acá cargamos cada cmb,txt o jtext con la info de la bd.
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select * from equipos where id_equipo = '" + idEquipo + "'");
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                //guardo en casa cmb, txt y jtextPane lo q hay en la bd.
                cmb_tipoEquipo.setSelectedItem(rs.getString("tipo_equipo"));
                cmb_marca.setSelectedItem(rs.getString("marca"));
                cmb_estatus.setSelectedItem(rs.getString("estatus"));
                txt_modelo.setText(rs.getString("modelo"));
                txt_numSerie.setText(rs.getString("num_serie"));
                txt_ultimaModificacion.setText(rs.getString("ultima_modificación"));

                String dia= "", mes = "", annio = "";//creo new var de fechas para traer las fechas de la bd.
                dia = rs.getString("dia_ingreso");
                mes = rs.getString("mes_ingreso");
                annio = rs.getString("anio_ingreso");

                txt_fechaIngreso.setText(dia + " del " + mes + " del " + annio);//guardo las fechas.

                jTextPane_dañosObservaciones.setText(rs.getString("observaciones"));
                jTextPane_comentariosTecnicos.setText(rs.getString("comentarios_técnicos"));
                jLabel_revisionTecnicaDe.setText("Comentarios y actualización del técnico: " + rs.getString("revision_tecnica_de"));

            } 
        } catch (SQLException e) {
            System.err.println("ERROR al consultar la información del equipo " + e);
        }
        setTitle("Equipos registrado con el ID " + idEquipo + " - Sesión de " + user );
        setSize(600, 520);
        setResizable(false);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_wallpaper.getWidth(),
                jLabel_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_wallpaper.setIcon(icono);
        this.repaint();

    }

    @Override
    public Image getIconImage() {
//luego de crear el metodo lo programamos, creamos un ob. y obtenemos la imagen del icono a colocar en interfaz.
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;//se o si hay q hacer el retorno del objeto.
/*de igual forma debemos ir a JFrame, clic derecho y propiedades, IconImage clic en ..., value from existing component,
        property, Iconimage, ok*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo = new javax.swing.JLabel();
        jLabel_nombreCliente = new javax.swing.JLabel();
        jLabel_tipoEquipo = new javax.swing.JLabel();
        jLabel_marca = new javax.swing.JLabel();
        jLabel_Modelo = new javax.swing.JLabel();
        jLabel_numeroSerie = new javax.swing.JLabel();
        jLabel_ultimaModificacion = new javax.swing.JLabel();
        jLabel_fechaIngreso = new javax.swing.JLabel();
        jLabel_estatus = new javax.swing.JLabel();
        jLabel_dañosObservaciones = new javax.swing.JLabel();
        jLabel_revisionTecnicaDe = new javax.swing.JLabel();
        txt_nombreCliente = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();
        txt_numSerie = new javax.swing.JTextField();
        txt_ultimaModificacion = new javax.swing.JTextField();
        txt_fechaIngreso = new javax.swing.JTextField();
        cmb_tipoEquipo = new javax.swing.JComboBox<>();
        cmb_marca = new javax.swing.JComboBox<>();
        cmb_estatus = new javax.swing.JComboBox<>();
        jScrollPane = new javax.swing.JScrollPane();
        jTextPane_dañosObservaciones = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane_comentariosTecnicos = new javax.swing.JTextPane();
        jLabel_footer = new javax.swing.JLabel();
        jButton_actualizarEquipo = new javax.swing.JButton();
        jLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_titulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel_titulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_titulo.setText("Información del Equipo");
        getContentPane().add(jLabel_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jLabel_nombreCliente.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_nombreCliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_nombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nombreCliente.setText("Nombre del cliente:");
        getContentPane().add(jLabel_nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel_tipoEquipo.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_tipoEquipo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_tipoEquipo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_tipoEquipo.setText("Tipo de equipo:");
        getContentPane().add(jLabel_tipoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel_marca.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_marca.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_marca.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_marca.setText("Marca:");
        getContentPane().add(jLabel_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel_Modelo.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_Modelo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_Modelo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Modelo.setText("Modelo:");
        getContentPane().add(jLabel_Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel_numeroSerie.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_numeroSerie.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_numeroSerie.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_numeroSerie.setText("Numero de serie:");
        getContentPane().add(jLabel_numeroSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel_ultimaModificacion.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_ultimaModificacion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_ultimaModificacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ultimaModificacion.setText("Ultima modificación por: ");
        getContentPane().add(jLabel_ultimaModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel_fechaIngreso.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_fechaIngreso.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_fechaIngreso.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_fechaIngreso.setText("Fecha de ingreso:");
        getContentPane().add(jLabel_fechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLabel_estatus.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_estatus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_estatus.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_estatus.setText("Estatus:");
        getContentPane().add(jLabel_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        jLabel_dañosObservaciones.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_dañosObservaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_dañosObservaciones.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_dañosObservaciones.setText("Daños reportados y observaciones:");
        getContentPane().add(jLabel_dañosObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel_revisionTecnicaDe.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_revisionTecnicaDe.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_revisionTecnicaDe.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_revisionTecnicaDe.setText("Comentario y actualización del técnico:");
        getContentPane().add(jLabel_revisionTecnicaDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        txt_nombreCliente.setEditable(false);
        txt_nombreCliente.setBackground(new java.awt.Color(153, 153, 255));
        txt_nombreCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_nombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombreCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nombreCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_nombreCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_nombreCliente.setEnabled(false);
        getContentPane().add(txt_nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, 30));

        txt_modelo.setBackground(new java.awt.Color(153, 153, 255));
        txt_modelo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_modelo.setForeground(new java.awt.Color(255, 255, 255));
        txt_modelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_modelo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txt_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 200, 30));

        txt_numSerie.setBackground(new java.awt.Color(153, 153, 255));
        txt_numSerie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_numSerie.setForeground(new java.awt.Color(255, 255, 255));
        txt_numSerie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_numSerie.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txt_numSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 200, 30));

        txt_ultimaModificacion.setEditable(false);
        txt_ultimaModificacion.setBackground(new java.awt.Color(153, 153, 255));
        txt_ultimaModificacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_ultimaModificacion.setForeground(new java.awt.Color(255, 255, 255));
        txt_ultimaModificacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_ultimaModificacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_ultimaModificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_ultimaModificacion.setEnabled(false);
        getContentPane().add(txt_ultimaModificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 200, 30));

        txt_fechaIngreso.setEditable(false);
        txt_fechaIngreso.setBackground(new java.awt.Color(153, 153, 255));
        txt_fechaIngreso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_fechaIngreso.setForeground(new java.awt.Color(255, 255, 255));
        txt_fechaIngreso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fechaIngreso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_fechaIngreso.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_fechaIngreso.setEnabled(false);
        getContentPane().add(txt_fechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 150, 30));

        cmb_tipoEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Desktop", "Impresora", "Multifuncion" }));
        getContentPane().add(cmb_tipoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        cmb_marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acer", "Apple", "Samsung", "Lenovo", "MSI" }));
        getContentPane().add(cmb_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        cmb_estatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo ingreso", "No reparado", "En revisión", "Reparado", "Entregado" }));
        getContentPane().add(cmb_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        jTextPane_dañosObservaciones.setEditable(false);
        jScrollPane.setViewportView(jTextPane_dañosObservaciones);

        getContentPane().add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 300, 120));

        jScrollPane2.setViewportView(jTextPane_comentariosTecnicos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 300, 120));

        jLabel_footer.setText("Creado por Luna Fabio");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 460, -1, -1));

        jButton_actualizarEquipo.setBackground(new java.awt.Color(153, 153, 255));
        jButton_actualizarEquipo.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jButton_actualizarEquipo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_actualizarEquipo.setText("Modificar y actualizar");
        jButton_actualizarEquipo.setBorder(null);
        jButton_actualizarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_actualizarEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_actualizarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 200, 35));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_actualizarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_actualizarEquipoActionPerformed
    //creamos estas var para guardar lo q este en los cmb, txt, jlabel.
       String estatus, ComentariosTecnicos, tecnico;
       
       estatus = cmb_estatus.getSelectedItem().toString();
       ComentariosTecnicos = jTextPane_comentariosTecnicos.getText();
       tecnico = jLabel_revisionTecnicaDe.getText();
       
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
     "update equipos set estatus=?, comentarios_técnicos=?, revision_tecnica_de=? where id_equipo = '" + idEquipo + "'");
            //guardamos en la bd los datos q colocamos en las var creadas.
            pst.setString(1, estatus);
            pst.setString(2, ComentariosTecnicos);
            pst.setString(3, user);
            
            pst.executeUpdate();
            cn.close();
            JOptionPane.showMessageDialog(null, "¡Actualización exitosa!");
            this.dispose();
            
        } catch (SQLException e) {
            System.err.println("ERROR al actualizar equipo." + e);
            JOptionPane.showMessageDialog(null, "Error al actualizar equipo. ¡Contacte al administrador.!");
        }
    }//GEN-LAST:event_jButton_actualizarEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacion_Equipo_Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacion_Equipo_Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacion_Equipo_Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion_Equipo_Tecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informacion_Equipo_Tecnico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_estatus;
    private javax.swing.JComboBox<String> cmb_marca;
    private javax.swing.JComboBox<String> cmb_tipoEquipo;
    private javax.swing.JButton jButton_actualizarEquipo;
    private javax.swing.JLabel jLabel_Modelo;
    private javax.swing.JLabel jLabel_dañosObservaciones;
    private javax.swing.JLabel jLabel_estatus;
    private javax.swing.JLabel jLabel_fechaIngreso;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JLabel jLabel_marca;
    private javax.swing.JLabel jLabel_nombreCliente;
    private javax.swing.JLabel jLabel_numeroSerie;
    private javax.swing.JLabel jLabel_revisionTecnicaDe;
    private javax.swing.JLabel jLabel_tipoEquipo;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JLabel jLabel_ultimaModificacion;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane_comentariosTecnicos;
    private javax.swing.JTextPane jTextPane_dañosObservaciones;
    private javax.swing.JTextField txt_fechaIngreso;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_nombreCliente;
    private javax.swing.JTextField txt_numSerie;
    private javax.swing.JTextField txt_ultimaModificacion;
    // End of variables declaration//GEN-END:variables

    public void Limpiar() {

        txt_nombreCliente.setText("");
        txt_modelo.setText("");
        txt_numSerie.setText("");
        txt_fechaIngreso.setText("");
        jTextPane_dañosObservaciones.setText("");
        
    }
}
