package ventanas;

import java.sql.*;
import clases.Conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.WindowConstants;
        

public class Registro_Cliente extends javax.swing.JFrame {

    String user;
    
    
    public Registro_Cliente() {
        initComponents();
        user = Login.user;
        
        
        
        setSize(540,440);
        setTitle("Registro nuevo cliente - sesion de " + user);
        setResizable(false);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        
        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
//creamos un ob. y le asignamos la distribucion y la escala de la imagen q ocupará toda la gráfica.
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), 
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);//le asignamos la escala al JLabel_w...
        this.repaint();//metodo para asegurar la acción.
    }
     @Override
    public Image getIconImage(){
//luego de crear el metodo lo programamos, creamos un ob. y obtenemos la imagen del icono a colocar en interfaz.
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;//se o si hay q hacer el retorno del objeto.
/*de igual forma debemos ir a JFrame, clic derecho y propiedades, IconImage clic en ..., value from existing component,
        property, Iconimage, ok*/
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_registroCliente = new javax.swing.JLabel();
        jLabel2_nombre = new javax.swing.JLabel();
        jLabel3_email = new javax.swing.JLabel();
        jLabel4_telefono = new javax.swing.JLabel();
        jLabel5_Direccion = new javax.swing.JLabel();
        jLabel__footer = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_telefono = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton_RegistrarClient = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_registroCliente.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_registroCliente.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel_registroCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_registroCliente.setText("Registro de Clientes");
        getContentPane().add(jLabel_registroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel2_nombre.setBackground(new java.awt.Color(153, 153, 255));
        jLabel2_nombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2_nombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2_nombre.setText("Nombre:");
        getContentPane().add(jLabel2_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel3_email.setBackground(new java.awt.Color(153, 153, 255));
        jLabel3_email.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3_email.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3_email.setText("Email:");
        getContentPane().add(jLabel3_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel4_telefono.setBackground(new java.awt.Color(153, 153, 255));
        jLabel4_telefono.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4_telefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4_telefono.setText("Telefono:");
        getContentPane().add(jLabel4_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel5_Direccion.setBackground(new java.awt.Color(153, 153, 255));
        jLabel5_Direccion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5_Direccion.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5_Direccion.setText("Direccion:");
        getContentPane().add(jLabel5_Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel__footer.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel__footer.setText("Creado por Luna Fabio");
        getContentPane().add(jLabel__footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        txt_nombre.setBackground(new java.awt.Color(153, 153, 255));
        txt_nombre.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 240, 30));

        txt_email.setBackground(new java.awt.Color(153, 153, 255));
        txt_email.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_email.setForeground(new java.awt.Color(255, 255, 255));
        txt_email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 240, 30));

        txt_telefono.setBackground(new java.awt.Color(153, 153, 255));
        txt_telefono.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_telefono.setForeground(new java.awt.Color(255, 255, 255));
        txt_telefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 240, 30));

        txt_direccion.setBackground(new java.awt.Color(153, 153, 255));
        txt_direccion.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_direccion.setForeground(new java.awt.Color(255, 255, 255));
        txt_direccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 240, 30));

        jLabel6.setBackground(new java.awt.Color(153, 153, 255));
        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Registrar Cliente");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, -1, -1));

        jButton_RegistrarClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        jButton_RegistrarClient.setBorder(null);
        jButton_RegistrarClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarClientActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_RegistrarClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 120, 100));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 421));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegistrarClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarClientActionPerformed
        
        int validacion = 0;//var. bandera.
        String nombre, email, telefono, direccion;
        
        nombre = txt_nombre.getText().trim();
        email = txt_email.getText().trim();
        telefono = txt_telefono.getText().trim();
        direccion = txt_direccion.getText().trim();
        
        if (nombre.equals("")) {
            txt_nombre.setBackground(Color.red);
            validacion++;
        }
        if (email.equals("")) {
            txt_email.setBackground(Color.red);
            validacion++;
        }
        if (telefono.equals("")) {
            txt_telefono.setBackground(Color.red);
            validacion++;//hace q la validacion tenga un valor !0
        }
        
        if (direccion.equals("")) {
            txt_direccion.setBackground(Color.red);
            validacion++;
        }
        
        if (validacion == 0) {
            
            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                   //instrucciones para guardar datos dentro de la bd.     
                        "insert into cliente values (?,?,?,?,?,?)");
                
                pst.setInt(1, 0);
                pst.setString(2, nombre);
                pst.setString(3, email);
                pst.setString(4, telefono);
                pst.setString(5, direccion);
                pst.setString(6, user);
               
                
                pst.executeUpdate();
                cn.close();
                
                Limpiar();//a este metodo lo programamos al final de todo el código.
                
                txt_nombre.setBackground(Color.green);
                txt_email.setBackground(Color.green);
                txt_telefono.setBackground(Color.green);
                txt_direccion.setBackground(Color.green);
                
                
                 JOptionPane.showMessageDialog(null, "Registro exitoso.");
                this.dispose();//metodo q libera recurso y cierra la interfaz
                
            } catch (SQLException e) {
                System.out.println("Error al registrar cliente." + e);
                JOptionPane.showMessageDialog(null, "Error al registrar cliente. Contacte al Administrador.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debes completar todos los campos.");
        }
    }//GEN-LAST:event_jButton_RegistrarClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_RegistrarClient;
    private javax.swing.JLabel jLabel2_nombre;
    private javax.swing.JLabel jLabel3_email;
    private javax.swing.JLabel jLabel4_telefono;
    private javax.swing.JLabel jLabel5_Direccion;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel__footer;
    private javax.swing.JLabel jLabel_registroCliente;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables

    public void Limpiar(){
        txt_nombre.setText("");
        txt_email.setText("");
        txt_telefono.setText("");
        txt_direccion.setText("");
        
    }

}
