package ventanas;
import java.sql.*;
import clases.Conexion;
import java.util.Calendar;//sirve para colocar fechas y horas.

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

public class Registro_Equipo extends javax.swing.JFrame {
    //creamos var en esta parte y en la parte de la accion del boton Registar_Equipo que esta abajo.
    int IDcliente_update = 0;
    String user, nomb_cliente;

    public Registro_Equipo() {
        initComponents();
        user = Login.user;
        IDcliente_update = Gestionar_Clientes.IDcliente_update;

        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                    "select nombre_cliente from cliente where id_cliente = '" + IDcliente_update + "'");
            ResultSet rs = pst.executeQuery();
    //conectamos a bd para traer el nomb del cliente y colocarlo en la new var.
            if (rs.next()) {
                nomb_cliente = rs.getString("nombre_cliente");
            }

        } catch (SQLException e) {
            System.err.println("Error al consultar nombre del cliente.");
        }//colocamos el nomb traido de la bd a nuestro titulo de interfaz.
        setTitle("Registrar nuevo equipo para " + nomb_cliente);
        setSize(630, 445);
        setResizable(false);
        setLocationRelativeTo(null);
    //estas lineas de codigo nos dice q si cerramos la interfaz, quedará la anterior disponible.
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_wallpaper.getWidth(),
                jLabel_wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_wallpaper.setIcon(icono);
        this.repaint();
    //colocamos la var anterior en el textField de la innterfaz de forma automatic
        jTextField_nombreCliente.setText(nomb_cliente);

    }

    @Override
    public Image getIconImage() {
//luego de crear el metodo lo programamos, creamos un ob. y obtenemos la imagen del icono a colocar en interfaz.
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/icon.png"));
        return retValue;//se o si hay q hacer el retorno del objeto.
/*de igual forma debemos ir a JFrame, clic derecho y propiedades, IconImage clic en ..., value from existing component,
        property, Iconimage, ok ok*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_titulo_info_cliente = new javax.swing.JLabel();
        jLabel_nombreCliente = new javax.swing.JLabel();
        jLabel_TipoEquipo = new javax.swing.JLabel();
        jLabel_Marca = new javax.swing.JLabel();
        jLabel_modelo = new javax.swing.JLabel();
        jLabel_NumeroSerie = new javax.swing.JLabel();
        jLabel_dañosYObservaciones = new javax.swing.JLabel();
        jTextField_nombreCliente = new javax.swing.JTextField();
        jTextField_NumeroSerie = new javax.swing.JTextField();
        jTextField_Modelo = new javax.swing.JTextField();
        jLabel_footer = new javax.swing.JLabel();
        jButton_RegistrarEquipo = new javax.swing.JButton();
        cmb_TipoEquipo = new javax.swing.JComboBox<>();
        cmb_Marca = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane_observaciones = new javax.swing.JTextPane();
        jLabel_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_titulo_info_cliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_titulo_info_cliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_titulo_info_cliente.setText("Registro de equipo");
        getContentPane().add(jLabel_titulo_info_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel_nombreCliente.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_nombreCliente.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_nombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nombreCliente.setText("Nombre del cliente:");
        getContentPane().add(jLabel_nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel_TipoEquipo.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_TipoEquipo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_TipoEquipo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TipoEquipo.setText("Tipo de equipo: ");
        getContentPane().add(jLabel_TipoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel_Marca.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_Marca.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_Marca.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Marca.setText("Marca:");
        getContentPane().add(jLabel_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel_modelo.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_modelo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_modelo.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_modelo.setText("Modelo:");
        getContentPane().add(jLabel_modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel_NumeroSerie.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_NumeroSerie.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_NumeroSerie.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_NumeroSerie.setText("Numero de serie:");
        getContentPane().add(jLabel_NumeroSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel_dañosYObservaciones.setBackground(new java.awt.Color(153, 153, 255));
        jLabel_dañosYObservaciones.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel_dañosYObservaciones.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_dañosYObservaciones.setText("Daños reportados y observaciones:");
        getContentPane().add(jLabel_dañosYObservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        jTextField_nombreCliente.setBackground(new java.awt.Color(153, 153, 255));
        jTextField_nombreCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_nombreCliente.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_nombreCliente.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_nombreCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jTextField_nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 200, 30));

        jTextField_NumeroSerie.setBackground(new java.awt.Color(153, 153, 255));
        jTextField_NumeroSerie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_NumeroSerie.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_NumeroSerie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_NumeroSerie.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jTextField_NumeroSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 200, 30));

        jTextField_Modelo.setBackground(new java.awt.Color(153, 153, 255));
        jTextField_Modelo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField_Modelo.setForeground(new java.awt.Color(255, 255, 255));
        jTextField_Modelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Modelo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(jTextField_Modelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 200, 30));

        jLabel_footer.setText("Creado por Luna Fabio");
        getContentPane().add(jLabel_footer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        jButton_RegistrarEquipo.setBackground(new java.awt.Color(153, 153, 255));
        jButton_RegistrarEquipo.setFont(new java.awt.Font("Arial Narrow", 0, 24)); // NOI18N
        jButton_RegistrarEquipo.setForeground(new java.awt.Color(255, 255, 255));
        jButton_RegistrarEquipo.setText("Registrar Equipo");
        jButton_RegistrarEquipo.setBorder(null);
        jButton_RegistrarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrarEquipoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_RegistrarEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 230, 35));

        cmb_TipoEquipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laptop", "Desktop", "Impresora", "Multifuncion", " " }));
        getContentPane().add(cmb_TipoEquipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        cmb_Marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acer", "Apple", "Samsung", "Lenovo", "MSI", " " }));
        getContentPane().add(cmb_Marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jScrollPane2.setViewportView(jTextPane_observaciones);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 350, 220));
        getContentPane().add(jLabel_wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegistrarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrarEquipoActionPerformed

        int validacion = 0;//var bandera.
        //creamos var q se llaman igual a las q tenemos en la bd y guardamos en ellas datos de la interfz. y new datos.
        String tipo_equipo, marca, modelo, num_serie, observaciones, dia_ingreso, mes_ingreso, annio_ingreso, estatus;

        tipo_equipo = cmb_TipoEquipo.getSelectedItem().toString();
        marca = cmb_Marca.getSelectedItem().toString();
        modelo = jTextField_Modelo.getText().trim();
        num_serie = jTextField_NumeroSerie.getText().trim();
        observaciones = jTextPane_observaciones.getText();
        estatus = "Nuevo ingreso";
    //llamamos a la class Calendar y le creamos un objeto, asi hacemos uso de la clase.
        Calendar calendar = Calendar.getInstance();

        dia_ingreso = Integer.toString(calendar.get(Calendar.DATE));//obtenemos dia.
        mes_ingreso = Integer.toString(calendar.get(Calendar.MONTH));//mes.
        annio_ingreso = Integer.toString(calendar.get(Calendar.YEAR));//año.

        if (modelo.equals("")) {
            jTextField_Modelo.setBackground(Color.red);
            validacion++;
        }
        if (num_serie.equals("")) {
            jTextField_NumeroSerie.setBackground(Color.red);
            validacion++;
        }//como es un textPane no coloreamos, sino llenamos con texto.
        if (observaciones.equals("")) {
            jTextPane_observaciones.setText("Sin observaciones");
        }
       //como valdacion es igual a 0, entra al campo de codigo y empieza a ejecutar lo q esta dentro.
        if (validacion == 0) {

            try {
                Connection cn = Conexion.conectar();
                PreparedStatement pst = cn.prepareStatement(
                //insertamos en la bd valores q estaran en la interfaz.
                        "Insert into equipos values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
        //si o si con el objeto pst. colocamos enteros o cadenas en el orden de la table de la bd.
                pst.setInt(1, 0);
                pst.setInt(2, IDcliente_update);
                pst.setString(3, tipo_equipo);
                pst.setString(4, marca);
                pst.setString(5, modelo);
                pst.setString(6, num_serie);
                pst.setString(7, dia_ingreso);
                pst.setString(8, mes_ingreso);
                pst.setString(9, annio_ingreso);
                pst.setString(10, observaciones);
                pst.setString(11, estatus);
                pst.setString(12, user);
                pst.setString(13, "");//queda para q el tecnico modifique
                pst.setString(14, "");//queda para q el tecnico modifique

                pst.executeUpdate();
                cn.close();

                jTextField_nombreCliente.setBackground(Color.GREEN);
                jTextField_Modelo.setBackground(Color.GREEN);
                jTextField_NumeroSerie.setBackground(Color.GREEN);
                
                JOptionPane.showMessageDialog(null, "¡Registro exitoso!");
                this.dispose();

            } catch (SQLException e) {
                System.err.println("ERROR al registrar equipo." + e);
                JOptionPane.showMessageDialog(null, "Error al registrar equipo. ¡Contacte al administrador!");

            }

        } else {
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos.");

        }

    }//GEN-LAST:event_jButton_RegistrarEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Equipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_Marca;
    private javax.swing.JComboBox<String> cmb_TipoEquipo;
    private javax.swing.JButton jButton_RegistrarEquipo;
    private javax.swing.JLabel jLabel_Marca;
    private javax.swing.JLabel jLabel_NumeroSerie;
    private javax.swing.JLabel jLabel_TipoEquipo;
    private javax.swing.JLabel jLabel_dañosYObservaciones;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JLabel jLabel_modelo;
    private javax.swing.JLabel jLabel_nombreCliente;
    private javax.swing.JLabel jLabel_titulo_info_cliente;
    private javax.swing.JLabel jLabel_wallpaper;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField_Modelo;
    private javax.swing.JTextField jTextField_NumeroSerie;
    private javax.swing.JTextField jTextField_nombreCliente;
    private javax.swing.JTextPane jTextPane_observaciones;
    // End of variables declaration//GEN-END:variables
}
